src/app.py
from flask import Flask, render_template
app = Flask(__name__)
app.config.from_object('config')
app.secret_key ='123'
from src.common.database import Database
from src.models.alerts.views import alert_blueprint
from src.models.stores.views import stores_blueprint
from src.models.users.views import user_blueprint
app.register_blueprint(user_blueprint,url_prefix='/users')
app.register_blueprint(alert_blueprint,url_prefix='/alerts')
app.register_blueprint(stores_blueprint,url_prefix='/stores')

@app.before_first_request
def init_db():
    Database.initialize()

@app.route('/')
def home():
    return render_template('home.jinja2')

src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for

from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decoraters
alert_blueprint = Blueprint('alerts',__name__)



@alert_blueprint.route('/new',methods=['GET','POST'])
@user_decoraters.requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price-limit'])
        item = Item(name,url)
        item.save_to_mongo()
        alert = Alert(session['email'],price_limit,item._id)
        alert.load_item_price()

    return render_template('alerts/create_alert.jinja2')



@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decoraters.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))

@alert_blueprint.route('/activate/<string:alert_id>')
@user_decoraters.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decoraters.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decoraters.requires_login
def get_alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template('alerts/alert.jinja2',alert=alert)


@alert_blueprint.route('/for_user/<string:user_id>')
def get_alerts_for_user(user_id):
    return render_template("underconstruction.jinja2")

@alert_blueprint.route('/check_price/<string:alert_id>')
def check_price(alert_id):
    alert = Alert.find_by_id(alert_id)
    alert.load_item_price()
    return redirect(url_for('.get_alert_page',alert_id=alert_id))

@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET','POST'])
def edit_alert(alert_id):
    if request.method == 'POST':
        price_limit = request.form['price-limit']
        alert = Alert.find_by_id(alert_id)
        alert.price_limit=price_limit
        alert.save_to_mongo()
        return redirect(url_for('users.user_alerts'))


    return render_template('alerts/edit_alert.jinja2',alert = Alert.find_by_id(alert_id))

src/models/items/views.py
from flask import Blueprint, render_template

item_blueprint = Blueprint('items', __name__)

@item_blueprint.route('/item/<string:name>')
def item_page(name):
    return render_template("underconstruction.jinja2")

@item_blueprint.route('/load')
def load_item():
    return render_template("underconstruction.jinja2")

src/models/stores/views.py
from flask import Blueprint, render_template, request, url_for, redirect, json
import src.models.users.decorators as user_decrators
from src.models.stores.store import Store

stores_blueprint = Blueprint('stores', __name__)


@stores_blueprint.route('/')
def index():
    stores = Store.find_all()
    return render_template("stores/store_index.jinja2", stores=stores)


@stores_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    store = Store.get_by_id(store_id)
    return render_template("stores/store.jinja2",store= store)


@stores_blueprint.route('/new',methods=['GET','POST'])
@user_decrators.requires_admin
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        prefix = request.form['prefix']
        tag = request.form['tag_name']
        query = json.loads(request.form['query'])
        store = Store(name,prefix,tag,query)
        store.save_to_mongo()
        return redirect(url_for('.index'))

    return render_template('stores/create_store.jinja2')


@stores_blueprint.route('/edit/<string:store_id>', methods=['GET','POST'])
@user_decrators.requires_admin
def edit_store(store_id):
    if request.method == 'POST':
        name = request.form['name']
        prefix = request.form['prefix']
        tag = request.form['tag_name']
        query = json.loads(request.form['query'])
        store = Store.get_by_id(store_id)
        store.name = name
        store.prefix = prefix
        store.tag_name = tag
        store.query = query
        store.save_to_mongo()
        return redirect(url_for('.index'))


    return render_template('stores/edit_store.jinja2',store = Store.get_by_id(store_id))


@stores_blueprint.route('/delete/<string:store_id>')
@user_decrators.requires_admin
def delete_store(store_id):
    store = Store.get_by_id(store_id)
    store.delete()
    return redirect('/stores')

src/models/users/views.py
from flask import Blueprint, request, session, url_for, redirect, render_template

import src.models.users.decorators as user_decoraters
from src.models.users import errors
from src.models.users.user import User

user_blueprint = Blueprint('users',__name__)

@user_blueprint.route('/login',methods=['GET','POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email,password):
                session['email'] = email
                return redirect(url_for('.user_alerts'))
        except errors.UserErrors as e:
            return e.message

    return render_template("users/login.jinja2")





@user_blueprint.route('/register',methods=['GET','POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email,password):
                session['email'] = email
                return redirect(url_for('.user_alerts'))
        except errors.UserErrors as e:
            return e.message

    return render_template("users/register.jinja2")

@user_blueprint.route('/logout')
@user_decoraters.requires_login
def logout_user():
    session['email']=None
    return redirect(url_for('home'))

@user_blueprint.route('/alters')
@user_decoraters.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    alerts = user.get_alerts()
    return render_template("users/alerts.jinja2",alerts=alerts)

@user_blueprint.route('/check_alerts/<string:user_id>')
def check_user_alerts(user_id):
    return render_template("underconstruction.jinja2")

src/templates/alerts/alert.jinja2
{% extends "base.jinja2" %}
{% block content %}

    <div class="page-header">
        <h1>Alert
            <small>for <i>{{ alert.item.name }}</i></small>
        </h1>
    </div>
    <p>Last Price <strong>{{ alert.item.price }}</strong></p>
    <p>Last Checked <strong>{{ alert.last_checked.strftime("%d-%m-%y at %H:%M") }}</strong></p>
    <div class="card ">
        <div class="card-body">
            <a class="btn btn-success" role="button" href="{{ alert.item.url }}" target="_blank">Visit Site</a>
            <a class="btn btn-warning" role="button" href="{{ url_for('alerts.edit_alert',alert_id=alert._id) }}">Edit
            </a>
            {% if alert.active %}
                <a class="btn btn-danger" role="button"
                   href="{{ url_for('alerts.deactivate_alert',alert_id=alert._id) }}">Deactivate</a>
            {% else %}
                <a class="btn btn-success" role="button"
                   href="{{ url_for('alerts.activate_alert',alert_id=alert._id) }}">Activate</a>
                <a class="btn btn-danger" role="button"
                   href="{{ url_for('alerts.delete_alert',alert_id=alert._id) }}">Permanent Delete Alert</a>
            {% endif %}
            <a class="btn btn-warning" role="button" href="{{ url_for('alerts.check_price',alert_id=alert._id) }}">Check
                Price</a>
        </div>
    </div>

{% endblock %}

src/templates/alerts/create_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Create Alert</h1>
    </div>
    <div class="form-size">
        <form method="post">
            <div class="form-group">
                <label for="name">Alert/Item Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="https://...">
            </div>
            <div class="form-group">
                <label for="price-limit">Price Limit</label>
                <input type="text" class="form-control" id="price-limit" name="price-limit" placeholder="45.00" aria-describedby="priceLimitBlock">
                <p id="priceLimitBlock"class="help-block">We will send you a email when price reaches or undergoes this</p>
            </div>
            <div>
            <button class="btn btn-default" type="submit"  style="padding-top: 20px" >Create</button>
                </div>
        </form>
    </div>
{% endblock %}

src/templates/alerts/edit_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Edit Alert</h1>
            <hr>
        </div>
    </div>
    <div class="form-size">
        <form action="{{ url_for('alerts.edit_alert',alert_id=alert._id) }}" method="post">
            <div class="form-group ">
                <label for="name">Alert/Item Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="{{ alert.item.name }}" disabled>
            </div>
            <div class="form-group ">
                <label for="prefix">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="{{ alert.item.url }}" disabled>
            </div>
            <div class="form-group ">
                <label for="prefix">Price Limit</label>
                <input type="text" class="form-control" id="price-limit" name="price-limit" placeholder="{{ alert.price_limit }}">
            </div>
            <button class="btn btn-primary" type="submit">
                Update
            </button>
        </form>
    </div>
{% endblock %}

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Price Alert</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'html_dependencies.jinja2' %}

</head>
<body >

<nav   class="navbar navbar-expand-lg navbar-light mine" style=" background-color: #cfd8c7;" >

    <a class="navbar-brand" href="/" title="Home" >Price Alert</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div  class="navbar-collapse collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for("stores.index")}}">Stores<span class="sr-only">(current)</span> </a>
            </li>

        </ul>
        {% if session['email'] %}
            <ul class="navbar-nav  navbar-right">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for("users.user_alerts")}}"><span class="fa fa-exclamation-triangle"></span> My Alerts </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for("users.logout_user")}}"><span class="fa fa-sign-out-alt" aria-hidden="true"></span> Log out</a>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav  navbar-right">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for("users.register_user")}}"><span class="fa fa-user" aria-hidden="true"></span> Sign Up </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for("users.login_user")}}"><span class="fa fa-sign-in-alt"></span> Log in</a>
                </li>
            </ul>
        {% endif %}

    </div>
</nav>

    {% block content %}

    {% endblock %}




  <div style="position: absolute; bottom: 0;background-color: #cfd8c7; width: 1535px; height: 40px;">

    <div class="align-center" style="padding-top: 7px">
    Designed by Abhinav Kushwah
    </div>
</div>

</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="jumbotron myhome">
        <h1 class="display-4">Price Alert</h1>
        <p class="lead">This a price alert portal for every enthusiast shopper.</p>
        <hr class="my-4">
        <p>We scan online websites to alert you of price drops in items that interests you.</p>
        <p>Just sign up , start by adding URL of the item that you wish to track, rest we will do!.</p>
        <a class="btn btn-primary btn-lg" href="{{ url_for("users.register_user")}}" role="button">Sign Up</a>
    </div>
{% endblock %}

src/templates/html_dependencies.jinja2
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

<link rel="stylesheet" href="../static/css/style.css">

src/templates/stores/create_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Create Store</h1>
            <hr>
        </div>
    </div>
    <div class="form-size">
        <form action="{{ url_for('stores.create_store') }}" method="post">
            <div class="form-group ">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="My Store">
            </div>
            <div class="form-group ">
                <label for="prefix">Store URL prefix</label>
                <input type="text" class="form-control" id="prefix" name="prefix" placeholder="http://www.mystore.com">
            </div>
            <div class="form-group ">
                <label for="tag_name">Tag</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" value="span" placeholder="span"
                       aria-describedby="storeTagNameHelp">
                <span id="storeTagNameHelp" class="help-block">What is the HTML tag of the item that contains the item price?(Usually <code>span</code>)</span>
            </div>
            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" name="query" value='{"id":"price-now"}' placeholder='{"id":"price-now"}'
                       aria-describedby="queryHelpBlock">
                <span id="queryHelpBlock" class="help-block">Json query to find specific tag with price.<br>Remember to use double quotation marks!)</span>
            </div>
            <button class="btn btn-primary" type="submit">
                Create
            </button>
        </form>
    </div>
{% endblock %}

src/templates/stores/edit_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Edit Store</h1>
            <hr>
        </div>
    </div>
    <div class="form-size">
        <form action="{{ url_for('stores.edit_store',store_id=store._id) }}" method="post">
            <div class="form-group ">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="{{ store.name }}" value="{{ store.name }}">
            </div>
            <div class="form-group ">
                <label for="prefix">Store URL prefix</label>
                <input type="text" class="form-control" id="prefix" name="prefix" placeholder="{{ store.prefix }}" value="{{ store.prefix }}">
            </div>
            <div class="form-group ">
                <label for="tag_name">Tag</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" value="{{ store.tag_name }}" placeholder="{{ store.tag_name }}"
                       aria-describedby="storeTagNameHelp">
                <span id="storeTagNameHelp" class="help-block">What is the HTML tag of the item that contains the item price?(Usually <code>span</code>)</span>
            </div>
            <div class="form-group">
                <label for="query">Query</label>
                <input type="text" class="form-control" id="query" name="query" value='{{ store.query | tojson }}' placeholder='{{ store.query | tojson }}'
                       aria-describedby="queryHelpBlock">
                <span id="queryHelpBlock" class="help-block">Json query to find specific tag with price.<br>Remember to use double quotation marks!)</span>
            </div>
            <button class="btn btn-primary" type="submit">
                Update
            </button>
        </form>
    </div>
{% endblock %}

src/templates/stores/store.jinja2
{% extends "base.jinja2" %}
{% block content %}

<div class="container">
    <div class="page-header">
        <h1>Stores <small><i>{{ store.name }} </i></small></h1>
    </div>
    <p>All URLs in this starts with prefix <strong>{{ store.prefix }}</strong></p>
    <div class="card">
        <div class="card-body">
            <a class="btn btn-success" href="{{ store.prefix }}" role="button" target="_blank">Visit</a>
            {% if session['email'] in config.ADMINS %}
            <a class="btn btn-warning" href="{{ url_for('stores.edit_store',store_id = store._id)}}" role="button">
                Edit Store
            </a>
            <a class="btn btn-danger" href="{{ url_for('stores.delete_store',store_id=store._id)}}" role="button">
                Permanently Delete Store
            </a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

src/templates/stores/store_index.jinja2
{% extends "base.jinja2" %}
{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Stores <small><i>Which we supports </i></small></h1>
    </div>
</div>
    <div class="list_group container">
       {% for store in stores %}
            <a href="{{ url_for('stores.store_page',store_id = store._id) }}" class="list-group-item" target="_blank">
                <h4 class="list-group-item-heading">{{ store.name }}</h4>
                <p class="list-group-item-text">All URL starts with {{ store.prefix }}</p>
            </a>
        {% endfor %}

    </div>
    {% if session['email'] in config.ADMINS %}
    <div class="container">
    <a href="{{ url_for('stores.create_store') }}" class="btn btn-success" >
        <span class="fa fa-plus"> Create Store</span>
    </a>
    </div>
    {% endif %}
{% endblock %}

src/templates/underconstruction.jinja2
{% extends "base.jinja2" %}
{% block content %}
<div class="bgimg">
  <div class="middle">
    <h1>COMING SOON</h1>
  </div>

</div>
{% endblock %}

src/templates/users/alerts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/users/alerts.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header ">
        <h1>Alerts<small> showing already existed alerts</small></h1>
    </div>
    <hr>
    <div class="list-group">
    {% for alert in alerts %}
        <a href="{{ url_for('alerts.get_alert_page',alert_id = alert._id) }}" class="list-group-item {{ "list-group-item-warning" if not alert.active else '' }}">
            <h4 class="list-group-item-heading " style="color: #1c25ba ">
                <span class="{{ 'far fa-lightbulb' if not alert.active else 'fas fa-lightbulb'   }}"></span>Alert for {{ alert.item.name }}</h4>
            <p class="list-group-item-text">Last Price found <strong>{{ alert.item.price }}</strong><br>
            Last Checked on <strong>{{ alert.last_checked.strftime("%d-%m-%y at %H:%M") }}</strong>
            </p>
        </a>
    {% endfor %}


    </div>
    <a class="btn btn-success"  href="{{ url_for('alerts.create_alert') }}"><span class="fa fa-plus"></span> Create Alert</a>

{% endblock %}

src/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/users/login.jinja2
{% extends "base.jinja2" %}
{% block content %}

    <div class="form-size">
        <form action="{{ url_for('users.login_user') }}" method="post">
            <div class="form-group ">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Log In</button>
        </form>
    </div>

{% endblock %}

src/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/templates/users/register.jinja2
{% extends "base.jinja2" %}
{% block content %}

    <div class="form-size">
        <form action="{{ url_for('users.register_user') }}" method="post">
            <div class="form-group ">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
    </div>

{% endblock %}

templates/alerts/alert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/alerts/create_alert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/alerts/edit_alert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/html_dependencies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/stores/create_store.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/stores/edit_store.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/stores/store.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>